In [1]:
import sys
print(sys.executable)

C:\Users\hp\Desktop\Fintech_Complaint_Analysis\venv\Scripts\python.exe

# Project: Fintech Complaint Risk Analysis

# 01_data_understanding.ipynb

1. Project & Dataset Overview
2. Import Libraries
3. Load Dataset
4. Dataset Shape & Columns
5. Data Types & Memory Usage
6. Missing Values Analysis
7. Target Business Columns Understanding
8. Initial Observations & Next Steps

In [2]:
## Step.1 Project & Dataset Overview

#Problem Statement:Fintech companies receive a high volume of customer complaints related to payments, banking, and financial services. Manual analysis of these complaints is inefficient and makes it difficult to quickly identify high-risk and urgent issues.This project aims to automate complaint analysis by using NLP to understand customer sentiment and assess risk for faster prioritization.

#Project Objective : To build an NLP-based system that analyzes fintech customer complaints, identifies sentiment, and assigns risk scores to prioritize high-impact issues for faster resolution.

In [3]:
## Step.2 Import Required Libraries (Code Cell)
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 200)

In [4]:
## Step.3 Load Dataset (Code Cell)

file_path = r"C:\Users\hp\Desktop\Fintech_Complaint_Analysis\data\raw\complaints.csv"

df = pd.read_csv(file_path)

In [5]:
df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2020-07-06,"Credit reporting, credit repair services, or other personal consumer reports",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the CFPB and chooses not to provide a public response,Experian Information Solutions Inc.,FL,346XX,NaN,Other,Web,2020-07-06,Closed with explanation,Yes,NaN,3730948
1,2025-11-25,Credit reporting or other personal consumer reports,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",GA,30311,NaN,NaN,Web,2025-11-25,In progress,Yes,NaN,17487731
2,2025-10-14,Credit reporting or other personal consumer reports,Credit reporting,Incorrect information on your report,Information is missing that should be on the report,My credit report contains incorrect and misleading items.,NaN,"EQUIFAX, INC.",TX,75062,NaN,Consent provided,Web,2025-10-14,Closed with non-monetary relief,Yes,NaN,16558024
3,2025-10-26,Credit reporting or other personal consumer reports,Credit reporting,Incorrect information on your report,Information belongs to someone else,Be sure that disputed accounts are taken down promptly in accordance with the law.,Company has responded to the consumer and the CFPB and chooses not to provide a public response,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,93619,NaN,Consent provided,Web,2025-10-26,Closed with non-monetary relief,Yes,NaN,16826857
4,2025-10-10,Credit reporting or other personal consumer reports,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",GA,30341,NaN,Consent not provided,Web,2025-10-10,Closed with non-monetary relief,Yes,NaN,16507707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12714861,2014-04-21,Credit card,NaN,Other,NaN,NaN,NaN,AMERICAN EXPRESS COMPANY,CA,92003,NaN,NaN,Web,2014-04-21,Closed with monetary relief,Yes,No,816552
12714862,2019-07-26,Mortgage,Conventional home mortgage,Struggling to pay mortgage,NaN,NaN,NaN,JPMORGAN CHASE & CO.,NaN,NaN,NaN,NaN,Referral,2019-07-29,Closed with explanation,Yes,NaN,3322081
12714863,2019-05-22,"Credit reporting, credit repair services, or other personal consumer reports",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the CFPB and chooses not to provide a public response,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",NaN,NaN,NaN,Consent not provided,Web,2019-05-22,Closed with explanation,Yes,NaN,3249858
12714864,2019-06-03,"Credit reporting, credit repair services, or other personal consumer reports",Credit reporting,Problem with a credit reporting company's investigation into an existing problem,Their investigation did not fix an error on your report,NaN,Company has responded to the consumer and the CFPB and chooses not to provide a public response,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",NaN,NaN,NaN,Consent not provided,Web,2019-06-03,Closed with non-monetary relief,Yes,NaN,3262839
12714865,2021-11-03,"Credit reporting, credit repair services, or other personal consumer reports",Credit reporting,Improper use of your report,Reporting company used your report improperly,"The consumer reporting agency, XXXX, has furnished my consumer report without my authorization. And gained monetary benefit by selling my information to another consumer reporting Agency. This hap...",Company has responded to the consumer and the CFPB and chooses not to provide a public response,"BANK OF AMERICA, NATIONAL ASSOCIATION",NaN,XXXXX,NaN,Consent provided,Web,2021-11-03,Closed with explanation,Yes,NaN,4869328

In [6]:
# Define Required Columns

import pandas as pd

file_path = r"C:\Users\hp\Desktop\Fintech_Complaint_Analysis\data\raw\complaints.csv"

cols = [
    'Consumer complaint narrative',
    'Product',
    'Issue',
    'Company',
    'Date received',
    'Company response to consumer' 
]

df = pd.read_csv(
    file_path,
    usecols=cols,
    nrows=30000
)

In [7]:
df

,Date received,Product,Issue,Consumer complaint narrative,Company,Company response to consumer
0,2020-07-06,"Credit reporting, credit repair services, or other personal consumer reports",Incorrect information on your report,NaN,Experian Information Solutions Inc.,Closed with explanation
1,2025-11-25,Credit reporting or other personal consumer reports,Incorrect information on your report,NaN,"EQUIFAX, INC.",In progress
2,2025-10-14,Credit reporting or other personal consumer reports,Incorrect information on your report,My credit report contains incorrect and misleading items.,"EQUIFAX, INC.",Closed with non-monetary relief
3,2025-10-26,Credit reporting or other personal consumer reports,Incorrect information on your report,Be sure that disputed accounts are taken down promptly in accordance with the law.,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",Closed with non-monetary relief
4,2025-10-10,Credit reporting or other personal consumer reports,Incorrect information on your report,NaN,"EQUIFAX, INC.",Closed with non-monetary relief
...,...,...,...,...,...,...
29995,2025-12-02,"Money transfer, virtual currency, or money service",Unauthorized transactions or other transaction problem,NaN,"Paypal Holdings, Inc",Closed with explanation
29996,2025-10-30,Credit reporting or other personal consumer reports,Problem with a company's investigation into an existing problem,NaN,"EQUIFAX, INC.",Closed with non-monetary relief
29997,2025-12-25,Credit reporting or other personal consumer reports,Improper use of your report,NaN,Experian Information Solutions Inc.,In progress
29998,2025-09-17,Credit reporting or other personal consumer reports,Incorrect information on your report,NaN,"EQUIFAX, INC.",Closed with non-monetary relief
29999,2014-08-11,Credit reporting,Unable to get credit report/credit score,NaN,Experian Information Solutions Inc.,Closed with explanation

In [8]:
## Step.4 Dataset Shape & Columns (Code Cell)

print("Dataset Shape:", df.shape)

Dataset Shape: (30000, 6)

In [9]:
df.columns

Index(['Date received', 'Product', 'Issue', 'Consumer complaint narrative',
       'Company', 'Company response to consumer'],
      dtype='object')

In [10]:
## Step.5  Data Types & Memory Usage

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date received                 30000 non-null  object
 1   Product                       30000 non-null  object
 2   Issue                         30000 non-null  object
 3   Consumer complaint narrative  3324 non-null   object
 4   Company                       30000 non-null  object
 5   Company response to consumer  30000 non-null  object
dtypes: object(6)
memory usage: 1.4+ MB

Date received                       0
Product                             0
Issue                               0
Consumer complaint narrative    26676
Company                             0
Company response to consumer        0
dtype: int64

In [11]:
## Step.6 Missing Values Analysis (Code Cell)

missing_df = df.isnull().sum().sort_values(ascending=False)
missing_df

Consumer complaint narrative    26676
Date received                       0
Product                             0
Issue                               0
Company                             0
Company response to consumer        0
dtype: int64

In [12]:
## Step.7 Understand Key Business Columns

# Key NLP Column

df['Consumer complaint narrative'].head(3)

0                                                          NaN
1                                                          NaN
2    My credit report contains incorrect and misleading items.
Name: Consumer complaint narrative, dtype: object

In [13]:
# Product Distribution

df['Product'].value_counts().head(10)

Product
Credit reporting or other personal consumer reports                             26118
Debt collection                                                                  1524
Credit reporting, credit repair services, or other personal consumer reports      635
Credit card                                                                       419
Checking or savings account                                                       408
Money transfer, virtual currency, or money service                                224
Mortgage                                                                          211
Vehicle loan or lease                                                             118
Student loan                                                                      102
Credit card or prepaid card                                                        91
Name: count, dtype: int64

In [14]:
# Issue Distribution

df['Issue'].value_counts().head(10)

Issue
Incorrect information on your report                                                16039
Improper use of your report                                                          5699
Problem with a company's investigation into an existing problem                      4767
Attempts to collect debt not owed                                                     580
Took or threatened to take negative or legal action                                   331
Written notification about debt                                                       308
Managing an account                                                                   243
False statements or representation                                                    206
Problem with a credit reporting company's investigation into an existing problem      167
Problem with a purchase shown on your statement                                       132
Name: count, dtype: int64

In [15]:
# Company Response

df['Company response to consumer'].value_counts().head(10)

Company response to consumer
In progress                        12028
Closed with explanation            11829
Closed with non-monetary relief     5968
Closed with monetary relief          127
Untimely response                     43
Closed without relief                  2
Closed                                 2
Closed with relief                     1
Name: count, dtype: int64

In [16]:
## Step.8 Initial Text Length Analysis

df['Consumer complaint narrative'] = df['Consumer complaint narrative'].fillna('')

df['text_length'] = df['Consumer complaint narrative'].apply(len)

df['text_length'].describe()

count    30000.000000
mean       119.173467
std        510.130683
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      18523.000000
Name: text_length, dtype: float64

### Initial Observations & Next Steps

# Initial Observations:
* The CFPB Consumer Complaint Database is a structured tabular dataset containing consumer complaint records from the financial services domain.
* The dataset consists of multiple feature types, including categorical, textual, and date-based columns.
* Missing values are present in certain columns and will require appropriate handling during preprocessing.
* The Consumer Complaint Narrative field can provide valuable insights through NLP techniques.
* The dataset contains business-relevant attributes such as product, company, issue, and complaint status that can support analytical and predictive   
  use cases.

# Next Steps:
* Perform detailed Exploratory Data Analysis (EDA) to understand data distributions, trends, and relationships between key variables.
* Apply data cleaning, preprocessing, and feature engineering techniques to prepare the dataset for machine learning and NLP modeling.